### ISSUE TITLE
API Impl tracking

### ISSUE THREAD

**Issue by Geobert** [ghost-in-the-sushi/efficio-server#1]
Implementation API
* [x] Création user
* [x] Login user
* [x] Logout
* [x] Suppression user
* [x] Creation magasin
* [x] Édition magasin
* [x] Suppression magasin
* [x] Lister tous les stores
* [x] Lister un magasin
* [x] Création rayon
* [x] Édition rayon
* [x] Suppression rayon
* [x] Création produit
* [x] Édition produit
* [x] Changement de poids
